### ISSUE TITLE
A question about the example of the "Getting started"

### ISSUE THREAD

**Issue by zijian1998** [eProsima/Micro-XRCE-DDS-docs#68]
Hi, I am a new hand who has read the specification of XRCE-DDS, and I have some problems with the sessionID and the client_key.  
In the specification clause 7.8.2.1, we said we will 

> Check if there is an existing XRCE ProxyClient object associated with the same client_key and, if so, compare the session_id of the existing ProxyClient with the one in the client_representation:
> - If a ProxyClient exists and has the same session_id, then the operation shall not perform any action and shall set the returnValue StatusValue to STATUS_OK.
> - If a ProxyClient exists and has a different session_id then the operation shall delete the existing XRCE ProxyClient object and subsequently take the same actions as if there had not been a ProxyClient associated with the client_key.

And [there](https://micro-xrce-dds.docs.eprosima.com/en/latest/getting_started.htm) are two clients in the deployment example, the first one is the configurator client and the second one is Publisher. They have the same client_key(0xAABBCCDD), so do they have the same sessionId when they connect to the agent? If they don't, should the Agent delete the ProxyClient and create a new one? After that, can the Publisher publish messages successfully? If they do, how to understand 

> The sessionId is unique to an XRCE Agent for a given XRCE Client.

in clause 8.3.2.1 of the specification?

Please help me! Thank you very much! 
  
Best regards

**Comment by pablogs9** [comment]
This exact example, [Deployment](https://github.com/eProsima/Micro-XRCE-DDS-Client/tree/master/examples/Deployment#deployment-example), is kind of special because it creates only one client, that why it has the same client key.

The point here is that the first code is intended to run in a high-end machine to create some DDS entities. Then the second code will need just the minimal profile of XRCE-DDS Client for interfacing with those entities that are already created, the use of this approach is that the second part of the code can fit in a very memory-constrained device due to the lack of entity creation methods.

I'm closing, do not hesitate to reopen if you have more questions.

**Comment by zijian1998** [comment]
Thank you very much for your answer. I have read the source code and it solved my question well.
However, I have another question about the function [*uxr_init_session*](https://github.com/eProsima/Micro-XRCE-DDS-Client/blob/master/src/c/core/session/session.c). 

```
······
158   uxr_init_session_info(&session->info, 0x81, key);
······
```

Does this line mean the sessionId is a fixed value 0x81 in the Micro-XRCE-DDS? So the agent will never delete the ProxyClient because of the different sessionID, right? and the following situation described by the specification will never happen, right?

> If a ProxyClient exists and has a different session_id then the operation shall delete the existing XRCE ProxyClient object and subsequently take the same actions as if there had not been a ProxyClient associated with the client_key.

Best regards

**Comment by pablogs9** [comment]
That's right
